import { useState, useEffect, useMemo } from 'react'
import { useLocation } from 'react-router-dom'
import {
  ResponsiveContainer, ComposedChart, Bar, Line, LineChart, XAxis, YAxis,
  CartesianGrid, Tooltip, Legend
} from 'recharts'
import { Plus, Info, RefreshCw, ChevronDown, X, Shield, Trash2, Search,
         TrendingUp, Calendar, DollarSign } from 'lucide-react'
import { useHedgePositions, useExposureSummary, useDashboardMetrics, useFxRates } from '@/hooks/useData'
import { useDerivedExposures } from '@/hooks/useDerivedExposures'
import { useLiveFxRates } from '@/hooks/useLiveFxRates'
import { useCombinedCoverage } from '@/hooks/useCombinedCoverage'
import { formatCurrency, formatDate, formatRate, daysUntil, currencyFlag } from '@/lib/utils'

import { toUsd } from '@/lib/fx'
import type { HedgePositionForm } from '@/types'

// Annualized forward premium per pair (interest rate differential, %).
// Used to derive the 12-month forward curve from the live spot rate.
const FORWARD_PREMIUM: Record<string, number> = {
  'USD/CAD': 0.39, 'EUR/CAD': 0.55, 'GBP/CAD': 0.57,
  'EUR/USD': 0.42, 'GBP/USD': 0.43,
}

/** Build a 12-month forward curve anchored to the current live spot. */
function buildForwardCurve(pair: string, liveSpot: number): { month: string; spot: number; forward: number }[] {
  const premium = FORWARD_PREMIUM[pair] ?? 0.40
  const now = new Date()
  return Array.from({ length: 12 }, (_, i) => {
    const d = new Date(now.getFullYear(), now.getMonth() + i + 1, 1)
    const month = d.toLocaleString('en-US', { month: 'short' })
    const forward = +(liveSpot * (1 + premium / 100 * (i + 1) / 12)).toFixed(4)
    return { month, spot: +liveSpot.toFixed(4), forward }
  })
}

// Live rate metadata per pair (spot, 1M forward, daily change pips, annualised fwd premium %)
const RATE_META: Record<string, { spot: number; fwd1m: number; change: number; premium: number; volume: string }> = {
  'USD/CAD': { spot: 1.3621, fwd1m: 1.3665, change: +12,  premium: +0.39, volume: '$4.2B' },
  'EUR/CAD': { spot: 1.4852, fwd1m: 1.4920, change: -8,   premium: +0.55, volume: '$2.8B' },
  'GBP/CAD': { spot: 1.7234, fwd1m: 1.7316, change: +5,   premium: +0.57, volume: '$1.9B' },
  'EUR/USD': { spot: 1.0895, fwd1m: 1.0933, change: -14,  premium: +0.42, volume: '$8.1B' },
  'GBP/USD': { spot: 1.2650, fwd1m: 1.2695, change: +3,   premium: +0.43, volume: '$3.5B' },
}

const RATE_CURVE_PAIRS = ['USD/CAD', 'EUR/CAD', 'GBP/CAD', 'EUR/USD', 'GBP/USD']


const MID_MARKET_DATA = [
  { pair: 'USD/CAD', spot: 1.3621, volume: '$4.2B', risk: 'Low' },
  { pair: 'EUR/CAD', spot: 1.4852, volume: '$2.8B', risk: 'Medium' },
  { pair: 'GBP/CAD', spot: 1.7234, volume: '$1.9B', risk: 'Low' },
  { pair: 'EUR/USD', spot: 1.0895, volume: '$8.1B', risk: 'High' },
  { pair: 'GBP/USD', spot: 1.2650, volume: '$3.5B', risk: 'Medium' },
]

const STRATEGY_TYPES = [
  { id: 'static', title: 'Static Hedging', desc: 'Fixed percentage hedge maintained consistently over time', icon: '📄' },
  { id: 'layered', title: 'Layered Hedging', desc: 'Build hedge positions incrementally over multiple periods', icon: '📄' },
  { id: 'micro', title: 'Micro Hedging', desc: 'Hedge individual transactions or exposures separately', icon: '📄' },
  { id: 'balance', title: 'Balance Sheet Hedging', desc: 'Hedge monetary assets and liabilities on the balance sheet', icon: '📄' },
]

const CURRENCY_PAIRS = [
  // Standard G10 pairs
  'EUR/USD', 'GBP/USD', 'USD/CAD', 'USD/JPY', 'AUD/USD', 'USD/CHF',
  'EUR/GBP', 'EUR/CAD', 'GBP/CAD', 'EUR/JPY', 'GBP/JPY', 'NZD/USD',
  // Inverted USD-base pairs (generated by derived exposure engine when policy base = USD)
  'CAD/USD', 'JPY/USD', 'CHF/USD', 'CNY/USD', 'SEK/USD', 'NOK/USD',
  'DKK/USD', 'HKD/USD', 'SGD/USD',
  // USD vs EM (standard)
  'USD/SEK', 'USD/NOK', 'USD/DKK', 'USD/HKD', 'USD/SGD',
  'USD/CNY', 'USD/KRW', 'USD/INR', 'USD/BRL', 'USD/ZAR',
  'USD/TRY', 'USD/IDR', 'USD/PHP', 'USD/THB', 'USD/MYR',
  // EM vs USD (inverted)
  'KRW/USD', 'INR/USD', 'BRL/USD', 'ZAR/USD', 'TRY/USD',
  'IDR/USD', 'PHP/USD', 'THB/USD', 'MYR/USD',
]
const INSTRUMENT_TYPES = [{ value: 'forward', label: 'Forward' }, { value: 'swap', label: 'FX Swap' }, { value: 'option', label: 'Option' }, { value: 'spot', label: 'Spot' }]
const BANKS = ['JPMorgan Chase', 'Goldman Sachs', 'Citibank', 'BMO Capital Markets', 'TD Securities', 'RBC Capital Markets', 'HSBC', 'Barclays', 'Deutsche Bank', 'BNP Paribas', 'Other']

function freshForm(): HedgePositionForm {
  return {
    instrument_type: 'forward', currency_pair: 'EUR/CAD', direction: 'sell',
    notional_base: 150000, contracted_rate: 1.362514, trade_date: new Date().toISOString().split('T')[0],
    value_date: '', counterparty_bank: 'BMO Capital Markets', reference_number: '', notes: '',
  }
}

type FormStep = 'select-strategy' | 'entry' | 'review' | 'success'

function RiskBadge({ level }: { level: string }) {
  const cls = { Low: 'badge-green', Medium: 'badge-amber', High: 'badge-red' }[level] ?? 'badge-gray'
  return <span className={`badge ${cls}`}>{level}</span>
}

export function HedgePage() {
  const { positions, loading, addPosition, deletePosition } = useHedgePositions()
  const { summary } = useExposureSummary()
  const location = useLocation()
  const [showForm, setShowForm] = useState(false)
  const [formStep, setFormStep] = useState<FormStep>('select-strategy')
  const [selectedStrategy, setSelectedStrategy] = useState<string | null>(null)
  const [form, setForm] = useState<HedgePositionForm>(freshForm)
  const [submitting, setSubmitting] = useState(false)
  const [formError, setFormError] = useState('')
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null)
  const [search, setSearch] = useState('')
  const [rateCurrencyTab, setRateCurrencyTab] = useState('USD/CAD')
  const [fee, setFee] = useState(200)
  const { metrics } = useDashboardMetrics()
  const { ratesMap, rates: liveRates } = useLiveFxRates()
  const { rates: fxRates } = useFxRates()
  const { combinedCoverage } = useCombinedCoverage()
  const { derivedExposures } = useDerivedExposures()

  // 12-month forward curve anchored to live spot for the selected pair
  const liveSpotForCurve = ratesMap[rateCurrencyTab] ?? RATE_META[rateCurrencyTab]?.spot ?? 1
  const rateCurveData = useMemo(
    () => buildForwardCurve(rateCurrencyTab, liveSpotForCurve),
    [rateCurrencyTab, liveSpotForCurve],
  )

  // FX Exposure chart: group derived exposures + hedge positions by settlement month (next 12m, USD equiv)
  const exposureChartData = useMemo(() => {
    const now = new Date()
    const buckets = Array.from({ length: 12 }, (_, i) => {
      const d = new Date(now.getFullYear(), now.getMonth() + i + 1, 1)
      const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
      const month = d.toLocaleString('en-US', { month: 'short' })
      return { key, month, expected: 0, hedged: 0 }
    })
    for (const exp of derivedExposures) {
      if (!exp.settlement_date) continue
      const key = exp.settlement_date.slice(0, 7)
      const b = buckets.find(b => b.key === key)
      if (b) b.expected += toUsd(exp.notional_base, exp.base_currency, fxRates)
    }
    for (const pos of positions) {
      if (!pos.value_date) continue
      const key = pos.value_date.slice(0, 7)
      const b = buckets.find(b => b.key === key)
      if (b) b.hedged += toUsd(pos.notional_base, pos.base_currency, fxRates)
    }
    return buckets.map(b => ({
      month: b.month,
      expected: Math.round(b.expected),
      hedged: Math.round(Math.min(b.hedged, b.expected)),
      coverage: b.expected > 0 ? Math.round(Math.min((b.hedged / b.expected) * 100, 100)) : 0,
    }))
  }, [derivedExposures, positions, fxRates])

  // Auto-open form when navigated from StrategyPage with a strategy pre-selected
  // OR from AdvisorPage with a pre-filled recommendation
  useEffect(() => {
    const state = location.state as any
    if (state?.strategy) {
      const match = STRATEGY_TYPES.find(s => s.title === state.strategy)
      if (match) {
        setSelectedStrategy(match.id)
        setFormStep('entry')
        setShowForm(true)
      }
    } else if (state?.prefill) {
      const p = state.prefill
      setForm(prev => ({
        ...prev,
        ...(p.instrument_type && { instrument_type: p.instrument_type }),
        ...(p.currency_pair   && { currency_pair: p.currency_pair }),
        ...(p.direction       && { direction: p.direction }),
        ...(p.notional_base   && { notional_base: p.notional_base }),
        ...(p.value_date      && { value_date: p.value_date }),
        ...(p.contracted_rate && p.contracted_rate > 0 && { contracted_rate: p.contracted_rate }),
        ...(p.base_currency   && { base_currency: p.base_currency }),
        ...(p.quote_currency  && { quote_currency: p.quote_currency }),
      }))
      setFormStep('entry')
      setShowForm(true)
    }
  }, [location.state])

  // If the form was opened via prefill but contracted_rate is still 0 (live rates
  // hadn't loaded yet when the effect ran), backfill with the live spot once available.
  useEffect(() => {
    if (!showForm || formStep !== 'entry') return
    if (form.contracted_rate && form.contracted_rate > 0) return  // already set
    const pair = form.currency_pair
    const live = ratesMap[pair]
      ?? (ratesMap[pair.split('/').reverse().join('/')]
          ? 1 / ratesMap[pair.split('/').reverse().join('/')]
          : 0)
    if (live > 0) set('contracted_rate', parseFloat(live.toFixed(6)))
  }, [ratesMap, showForm, formStep, form.currency_pair, form.contracted_rate])

  const [baseCcy, quoteCcy] = form.currency_pair.split('/')
  const quotedNotional = form.notional_base && form.contracted_rate ? form.notional_base * form.contracted_rate : 0

  const filtered = positions.filter(p =>
    !search || [p.currency_pair, p.counterparty_bank ?? '', p.reference_number ?? '']
      .some(s => s.toLowerCase().includes(search.toLowerCase()))
  )

  function set<K extends keyof HedgePositionForm>(k: K, v: HedgePositionForm[K]) {
    setForm(f => ({ ...f, [k]: v }))
  }

  const totalHedgedUsd = positions.reduce((s, p) => s + toUsd(p.notional_base, p.base_currency, ratesMap), 0)
  const uniquePairs = new Set(positions.map(p => p.currency_pair))
  const byPair: Record<string, number> = {}
  positions.forEach(p => { byPair[p.currency_pair] = (byPair[p.currency_pair] ?? 0) + p.notional_base })

  async function handleSubmit() {
    setFormError('')
    if (!form.notional_base || form.notional_base <= 0) { setFormError('Enter a valid notional amount'); return }
    if (!form.contracted_rate || form.contracted_rate <= 0) { setFormError('Enter a valid contracted rate'); return }
    if (!form.value_date) { setFormError('Settlement date is required'); return }
    if (new Date(form.value_date) <= new Date(form.trade_date)) { setFormError('Settlement date must be after trade date'); return }
    if (formStep === 'entry') { setFormStep('review'); return }
    setSubmitting(true)
    const [base, quote] = form.currency_pair.split('/')
    const { error } = await addPosition({ ...form, base_currency: base, quote_currency: quote, notional_usd: null, status: 'active' } as any)
    setSubmitting(false)
    if (error) { setFormError(error); return }
    setFormStep('success')
  }

  function closeForm() {
    setShowForm(false)
    setFormStep('select-strategy')
    setSelectedStrategy(null)
    setForm(freshForm())
    setFormError('')
  }

  return (
    <div className="fade-in">
      {/* Page Header */}
      <div className="page-header">
        <div>
          <h1 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--text-primary)' }}>Hedge</h1>
          <p style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', marginTop: '0.125rem' }}>Hedge your FX exposure in a few clicks</p>
        </div>
        <button className="btn btn-primary btn-sm" onClick={() => { setShowForm(true); setFormStep('select-strategy') }}>
          <Plus size={13} /> Add Hedge
        </button>
      </div>

      <div className="page-content">

        {/* Summary stat tiles */}
        {!loading && positions.length > 0 && (() => {
          const nearest = positions[0]  // sorted by value_date asc
          const nearestDays = daysUntil(nearest.value_date)
          // Compute total unrealized P&L (USD) across all positions
          const totalPnlUsd = positions.reduce((s, p) => {
            const currentRate = ratesMap[p.currency_pair] ?? p.contracted_rate
            const diff = p.direction === 'buy'
              ? currentRate - p.contracted_rate
              : p.contracted_rate - currentRate
            let pnl = diff * p.notional_base
            if (p.currency_pair.startsWith('USD/') && currentRate > 0) pnl = pnl / currentRate
            return s + pnl
          }, 0)
          return (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.75rem', marginBottom: '1rem' }}>
              {[
                {
                  label: 'Total Notional Hedged',
                  value: formatCurrency(totalHedgedUsd, 'USD', true),
                  sub: `${positions.length} position${positions.length !== 1 ? 's' : ''} across ${uniquePairs.size} pair${uniquePairs.size !== 1 ? 's' : ''}`,
                  icon: DollarSign, color: 'var(--teal)', bg: '#f0fdfa',
                },
                {
                  label: 'Nearest Maturity',
                  value: nearestDays <= 0 ? 'Today' : `${nearestDays}d`,
                  sub: formatDate(nearest.value_date) + ' · ' + nearest.currency_pair,
                  icon: Calendar,
                  color: nearestDays <= 7 ? 'var(--red)' : nearestDays <= 30 ? 'var(--amber)' : 'var(--teal)',
                  bg: nearestDays <= 7 ? '#fef2f2' : nearestDays <= 30 ? '#fffbeb' : '#f0fdfa',
                },
                {
                  label: 'Unrealized P&L',
                  value: (totalPnlUsd >= 0 ? '+' : '') + formatCurrency(Math.abs(totalPnlUsd), 'USD', true),
                  sub: totalPnlUsd >= 0 ? 'net gain across all positions' : 'net loss across all positions',
                  icon: TrendingUp,
                  color: totalPnlUsd >= 0 ? '#10b981' : '#ef4444',
                  bg: totalPnlUsd >= 0 ? '#f0fdfa' : '#fef2f2',
                },
              ].map(({ label, value, sub, icon: Icon, color, bg }) => (
                <div key={label} className="card" style={{ padding: '1rem' }}>
                  <div style={{ width: 32, height: 32, borderRadius: 'var(--r-sm)', background: bg, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '0.625rem' }}>
                    <Icon size={15} color={color} />
                  </div>
                  <div style={{ fontWeight: 700, fontSize: '1.375rem', fontFamily: 'var(--font-mono)', color: 'var(--text-primary)', letterSpacing: '-0.02em', marginBottom: '0.25rem' }}>
                    {value}
                  </div>
                  <div style={{ fontSize: '0.75rem', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '0.125rem' }}>{label}</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>{sub}</div>
                </div>
              ))}
            </div>
          )
        })()}

        {/* Two column layout */}
        <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: '1rem', marginBottom: '1rem' }}>

          {/* Left Column */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {/* FX Rate Curve */}
            <div className="card" style={{ padding: 0 }}>
              {/* Header */}
              <div style={{ padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                  <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>FX Rate Curve</span>
                  <Info size={13} color="var(--text-muted)" />
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>12-month forward curve</span>
                  <button style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', display: 'flex' }}
                    title="Refresh rates"><RefreshCw size={13} /></button>
                </div>
              </div>

              {/* Currency pair tabs */}
              <div style={{ padding: '0.75rem 1.25rem 0', borderBottom: '1px solid var(--border)' }}>
                <div className="pill-tabs" style={{ display: 'inline-flex' }}>
                  {RATE_CURVE_PAIRS.map(p => (
                    <button
                      key={p}
                      className={`pill-tab ${rateCurrencyTab === p ? 'active' : ''}`}
                      onClick={() => setRateCurrencyTab(p)}
                    >
                      {p}
                    </button>
                  ))}
                </div>
              </div>

              {/* Rate stats bar */}
              {(() => {
                const meta = RATE_META[rateCurrencyTab]
                if (!meta) return null
                const liveSpot = ratesMap[rateCurrencyTab] ?? meta.spot
                const fwd1m = liveSpot * (1 + meta.premium / 100 / 12)
                const spread = Math.round((fwd1m - liveSpot) * 10000)
                const liveEntry = liveRates.find(r => r.pair === rateCurrencyTab)
                const changeAbs = liveEntry ? liveEntry.changeAbs : null
                const changePips = changeAbs !== null ? Math.round(changeAbs * 10000) : meta.change
                const changePos = changePips >= 0
                return (
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', padding: '0.75rem 1.25rem', gap: '0.5rem', borderBottom: '1px solid var(--border)', background: 'var(--bg-surface)' }}>
                    <div>
                      <div style={{ fontSize: '0.69rem', color: 'var(--text-muted)', marginBottom: '0.2rem', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Live Spot</div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, fontSize: '0.9375rem' }}>{liveSpot.toFixed(4)}</div>
                    </div>
                    <div>
                      <div style={{ fontSize: '0.69rem', color: 'var(--text-muted)', marginBottom: '0.2rem', textTransform: 'uppercase', letterSpacing: '0.04em' }}>1M Forward (est.)</div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, fontSize: '0.9375rem', color: 'var(--teal-dark)' }}>{fwd1m.toFixed(4)}</div>
                    </div>
                    <div>
                      <div style={{ fontSize: '0.69rem', color: 'var(--text-muted)', marginBottom: '0.2rem', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Fwd Spread</div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 600, fontSize: '0.9375rem', color: '#6366f1' }}>
                        {spread > 0 ? '+' : ''}{spread} pips
                      </div>
                    </div>
                    <div>
                      <div style={{ fontSize: '0.69rem', color: 'var(--text-muted)', marginBottom: '0.2rem', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Daily Chg</div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 600, fontSize: '0.9375rem', color: changePips === 0 ? 'var(--text-muted)' : changePos ? 'var(--green)' : 'var(--red)' }}>
                        {changePips === 0 ? '— pips' : `${changePos ? '▲' : '▼'} ${Math.abs(changePips)} pips`}
                      </div>
                    </div>
                  </div>
                )
              })()}

              {/* Chart */}
              <div style={{ padding: '0.875rem 1.25rem 1rem', height: 180 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={rateCurveData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" vertical={false} />
                    <XAxis dataKey="month" tick={{ fontSize: 10, fill: 'var(--text-muted)' }} axisLine={false} tickLine={false} />
                    <YAxis
                      domain={['auto', 'auto']}
                      tick={{ fontSize: 10, fill: 'var(--text-muted)' }}
                      tickFormatter={v => v.toFixed(3)}
                      axisLine={false} tickLine={false}
                      width={48}
                    />
                    <Tooltip
                      contentStyle={{ background: '#fff', border: '1px solid var(--border)', borderRadius: 8, fontSize: 12 }}
                      formatter={(v: number, name: string) => [v.toFixed(4), name]}
                      labelFormatter={label => `${label} — ${rateCurrencyTab}`}
                    />
                    <Legend wrapperStyle={{ fontSize: 11, paddingTop: 4 }} />
                    <Line type="monotone" dataKey="spot" name="Spot" stroke="var(--teal)" strokeWidth={2} dot={false} activeDot={{ r: 4 }} />
                    <Line type="monotone" dataKey="forward" name="Forward" stroke="#6366f1" strokeWidth={2} dot={false} strokeDasharray="6 3" activeDot={{ r: 4 }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* FX Exposure Chart */}
            <div className="card" style={{ padding: 0 }}>
              <div style={{ padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>FX Exposure</span>
                <Info size={13} color="var(--text-muted)" />
                <span className="badge badge-teal" style={{ marginLeft: 'auto' }}>12-month · USD equiv</span>
              </div>
              <div style={{ padding: '1rem 1.25rem', height: 220 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <ComposedChart data={exposureChartData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                    <XAxis dataKey="month" tick={{ fontSize: 11, fill: 'var(--text-muted)' }} />
                    <YAxis yAxisId="left" tick={{ fontSize: 11, fill: 'var(--text-muted)' }} tickFormatter={v => `$${(v/1000000).toFixed(1)}M`} />
                    <YAxis yAxisId="right" orientation="right" domain={[0, 100]} tick={{ fontSize: 11, fill: 'var(--text-muted)' }} tickFormatter={v => `${v}%`} />
                    <Tooltip contentStyle={{ background: '#fff', border: '1px solid var(--border)', borderRadius: 8, fontSize: 12 }}
                      formatter={(v: number, name: string) => name === 'coverage' ? `${v}%` : formatCurrency(v, 'USD', true)} />
                    <Legend wrapperStyle={{ fontSize: 12 }} />
                    <Bar yAxisId="left" dataKey="expected" name="Expected" fill="#e2e8f0" radius={[3,3,0,0]} />
                    <Bar yAxisId="left" dataKey="hedged" name="Hedged" fill="var(--teal)" radius={[3,3,0,0]} />
                    <Line yAxisId="right" type="monotone" dataKey="coverage" name="Coverage %" stroke="#0b1526" strokeWidth={2} dot={false} />
                  </ComposedChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          {/* Right Column */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {/* Mid-Market Swap Rate */}
            <div className="card" style={{ padding: 0 }}>
              <div style={{ padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                  <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>Mid-Market Swap Rate</span>
                  <Info size={13} color="var(--text-muted)" />
                </div>
                <button style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--teal)' }}><RefreshCw size={13} /></button>
              </div>
              <table className="data-table">
                <thead><tr><th>Pair</th><th className="text-right">Spot Rate</th><th className="text-right">Chg</th><th>Risk</th></tr></thead>
                <tbody>
                  {MID_MARKET_DATA.map((row, i) => {
                    const liveSpot = ratesMap[row.pair] ?? row.spot
                    const liveEntry = liveRates.find(r => r.pair === row.pair)
                    const chg = liveEntry?.change ?? 'flat'
                    const chgPct = liveEntry ? liveEntry.changePct : 0
                    return (
                      <tr key={i}>
                        <td style={{ fontWeight: 600, fontFamily: 'var(--font-mono)' }}>{row.pair}</td>
                        <td className="text-right mono">{liveSpot.toFixed(4)}</td>
                        <td className="text-right" style={{ fontFamily: 'var(--font-mono)', fontSize: '0.8125rem', color: chg === 'up' ? 'var(--green)' : chg === 'down' ? 'var(--red)' : 'var(--text-muted)' }}>
                          {chg === 'flat' || chgPct === 0 ? '—' : `${chg === 'up' ? '▲' : '▼'} ${Math.abs(chgPct).toFixed(2)}%`}
                        </td>
                        <td><RiskBadge level={row.risk} /></td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
              <div style={{ padding: '0.625rem 1.25rem', borderTop: '1px solid var(--border)' }}>
                <button className="btn btn-ghost btn-sm" style={{ width: '100%', justifyContent: 'center' }}>
                  <Plus size={13} /> Add New
                </button>
              </div>
            </div>

            {/* Exposure Summary */}
            <div className="card" style={{ padding: 0 }}>
              <div style={{ padding: '1rem 1.25rem', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>Exposure Summary</span>
                <Info size={13} color="var(--text-muted)" />
              </div>
              <div style={{ padding: '1rem 1.25rem' }}>
                {(() => {
                  const totalExp    = combinedCoverage.reduce((s, c) => s + toUsd(Math.abs(c.net_exposure), c.base_currency, fxRates), 0)
                  const totalHdg    = combinedCoverage.reduce((s, c) => s + toUsd(c.total_hedged, c.base_currency, fxRates), 0)
                  const hedgePct    = totalExp > 0 ? (totalHdg / totalExp) * 100 : 0
                  const unhedgedAmt = Math.max(0, totalExp - totalHdg)
                  const sorted = [...combinedCoverage].sort((a, b) =>
                    toUsd(Math.abs(b.net_exposure), b.base_currency, fxRates) -
                    toUsd(Math.abs(a.net_exposure), a.base_currency, fxRates)
                  )
                  return (
                    <>
                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem' }}>
                        <div>
                          <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>Net Exposure</div>
                          <div style={{ fontWeight: 700, fontSize: '1.375rem', fontFamily: 'var(--font-mono)', letterSpacing: '-0.02em' }}>
                            {totalExp > 0 ? formatCurrency(totalExp, 'USD', true) : '—'}
                          </div>
                        </div>
                        <div style={{ textAlign: 'right' }}>
                          <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>Hedge Ratio</div>
                          <div style={{ fontWeight: 700, fontSize: '1.375rem', color: 'var(--teal-dark)', fontFamily: 'var(--font-mono)' }}>
                            {totalExp > 0 ? `${hedgePct.toFixed(1)}%` : '—'}
                          </div>
                        </div>
                      </div>
                      <div style={{ height: 8, background: '#e2e8f0', borderRadius: 4, overflow: 'hidden', marginBottom: '0.625rem' }}>
                        <div style={{ height: '100%', width: `${Math.min(hedgePct, 100)}%`, background: 'var(--teal)', borderRadius: 4, transition: 'width 0.6s' }} />
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <div>
                          <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>Hedged</div>
                          <div style={{ fontWeight: 600, fontSize: '0.875rem', fontFamily: 'var(--font-mono)', color: 'var(--teal-dark)' }}>
                            {totalHdg > 0 ? formatCurrency(totalHdg, 'USD', true) : '—'}
                          </div>
                        </div>
                        <div style={{ textAlign: 'right' }}>
                          <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>Unhedged</div>
                          <div style={{ fontWeight: 600, fontSize: '0.875rem', fontFamily: 'var(--font-mono)', color: unhedgedAmt > 0 ? 'var(--red)' : 'var(--green)' }}>
                            {formatCurrency(unhedgedAmt, 'USD', true)}
                          </div>
                        </div>
                      </div>
                      {sorted.length > 0 && (
                        <div style={{ marginTop: '1rem', paddingTop: '0.75rem', borderTop: '1px solid var(--border-dim)' }}>
                          {sorted.map(c => {
                            const pct = Math.abs(c.net_exposure) > 0
                              ? Math.min((c.total_hedged / Math.abs(c.net_exposure)) * 100, 100)
                              : 0
                            return (
                              <div key={c.currency_pair} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
                                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', width: 70 }}>{c.currency_pair}</span>
                                <div style={{ flex: 1, height: 4, background: '#e2e8f0', borderRadius: 2 }}>
                                  <div style={{ height: '100%', width: `${pct}%`, background: 'var(--teal)', borderRadius: 2 }} />
                                </div>
                                <span style={{ fontSize: '0.72rem', fontWeight: 600, color: 'var(--teal-dark)', width: 35, textAlign: 'right' }}>{pct.toFixed(0)}%</span>
                              </div>
                            )
                          })}
                        </div>
                      )}
                    </>
                  )
                })()}
              </div>
            </div>
          </div>
        </div>

        {/* Hedge Positions Table */}
        <div style={{ marginBottom: '1rem' }}>
          <div style={{ display: 'flex', gap: '0.625rem', marginBottom: '0.75rem', alignItems: 'center' }}>
            <span style={{ fontWeight: 600, fontSize: '0.9rem' }}>Hedge Positions</span>
            <span style={{ color: 'var(--text-muted)', fontSize: '0.75rem' }}>({positions.length} active)</span>
            <div style={{ marginLeft: 'auto', position: 'relative' }}>
              <Search size={14} style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)', pointerEvents: 'none' }} />
              <input className="input" style={{ paddingLeft: '2.25rem', width: 240 }} placeholder="Search currency, bank…"
                value={search} onChange={e => setSearch(e.target.value)} />
            </div>
          </div>

          <div className="card" style={{ padding: 0 }}>
            {loading ? (
              <div style={{ display: 'flex', justifyContent: 'center', padding: '2rem' }}><div className="spinner" style={{ width: 24, height: 24 }} /></div>
            ) : filtered.length === 0 ? (
              <div className="empty-state">
                <Shield size={32} />
                <h3>No hedge positions{search ? ' matching' : ''}</h3>
                <p>Add your first hedge using the "Add Hedge" button above.</p>
                <button className="btn btn-primary btn-sm" onClick={() => { setShowForm(true); setFormStep('select-strategy') }}>
                  <Plus size={13} /> Add Hedge
                </button>
              </div>
            ) : (
              <div style={{ overflowX: 'auto' }}>
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Instrument</th><th>Currency Pair</th><th>Direction</th>
                      <th className="text-right">Notional</th><th className="text-right">Rate</th>
                      <th>Trade Date</th><th>Settlement</th><th>Days</th>
                      <th>Counterparty</th><th>Reference</th><th />
                    </tr>
                  </thead>
                  <tbody>
                    {filtered.map(p => {
                      const days = daysUntil(p.value_date)
                      return (
                        <tr key={p.id}>
                          <td><span className="badge badge-teal">{p.instrument_type}</span></td>
                          <td>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
                              <span>{currencyFlag(p.base_currency)}</span>
                              <span style={{ fontWeight: 600, fontFamily: 'var(--font-mono)' }}>{p.currency_pair}</span>
                            </div>
                          </td>
                          <td><span className={`badge badge-${p.direction === 'buy' ? 'green' : 'blue'}`}>{p.direction === 'buy' ? '↑ Buy' : '↓ Sell'} {p.base_currency}</span></td>
                          <td className="text-right mono" style={{ fontWeight: 500 }}>{formatCurrency(p.notional_base, p.base_currency)}</td>
                          <td className="text-right mono">{formatRate(p.contracted_rate)}</td>
                          <td style={{ color: 'var(--text-secondary)' }}>{formatDate(p.trade_date)}</td>
                          <td style={{ color: 'var(--text-secondary)' }}>{formatDate(p.value_date)}</td>
                          <td><span style={{ fontSize: '0.8125rem', fontWeight: 500, color: days < 0 ? 'var(--text-muted)' : days <= 7 ? 'var(--red)' : days <= 30 ? 'var(--amber)' : 'var(--teal-dark)' }}>{days < 0 ? 'Expired' : `${days}d`}</span></td>
                          <td style={{ color: 'var(--text-secondary)' }}>{p.counterparty_bank || '—'}</td>
                          <td style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: '0.8125rem' }}>{p.reference_number || '—'}</td>
                          <td>
                            {confirmDeleteId === p.id ? (
                              <div style={{ display: 'flex', gap: '0.25rem' }}>
                                <button className="btn btn-danger btn-sm" onClick={() => { deletePosition(p.id); setConfirmDeleteId(null) }}>Delete</button>
                                <button className="btn btn-ghost btn-sm" onClick={() => setConfirmDeleteId(null)}>Keep</button>
                              </div>
                            ) : (
                              <button onClick={() => setConfirmDeleteId(p.id)}
                                style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', padding: '0.25rem', borderRadius: 'var(--r-sm)' }}
                                onMouseEnter={e => (e.currentTarget.style.color = 'var(--red)')}
                                onMouseLeave={e => (e.currentTarget.style.color = 'var(--text-muted)')}>
                                <Trash2 size={13} />
                              </button>
                            )}
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Modal */}
      {showForm && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', backdropFilter: 'blur(4px)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50, padding: '1rem' }}>
          <div className="card fade-in" style={{ width: '100%', maxWidth: formStep === 'select-strategy' ? 560 : 480, maxHeight: '90vh', overflowY: 'auto', background: '#fff' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.25rem' }}>
              <div>
                <h3 style={{ fontWeight: 700, color: 'var(--text-primary)' }}>
                  {formStep === 'select-strategy' ? 'Create a New Hedge Strategy' :
                   formStep === 'entry' ? 'FX Forward' :
                   formStep === 'review' ? 'Review & Confirm' : 'Transaction Sent'}
                </h3>
                {formStep === 'entry' && <p style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', marginTop: '0.1rem' }}>Fill in the trade details below</p>}
              </div>
              <button onClick={closeForm} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}><X size={18} /></button>
            </div>

            {/* Select Strategy Step */}
            {formStep === 'select-strategy' && (
              <div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', marginBottom: '1.25rem' }}>
                  {STRATEGY_TYPES.map(s => (
                    <div key={s.id}
                      onClick={() => { setSelectedStrategy(s.id); setFormStep('entry') }}
                      style={{ padding: '1.25rem', border: `1px solid ${selectedStrategy === s.id ? 'var(--teal)' : 'var(--border)'}`, borderRadius: 'var(--r-lg)', cursor: 'pointer', transition: 'all 0.15s', background: selectedStrategy === s.id ? '#f0fdfa' : 'var(--bg-surface)' }}
                      onMouseEnter={e => (e.currentTarget.style.borderColor = 'var(--teal)')}
                      onMouseLeave={e => { if (selectedStrategy !== s.id) (e.currentTarget.style.borderColor = 'var(--border)') }}>
                      <div style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>{s.icon}</div>
                      <div style={{ fontWeight: 600, fontSize: '0.875rem', marginBottom: '0.25rem' }}>{s.title}</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{s.desc}</div>
                    </div>
                  ))}
                </div>
                <button className="btn btn-ghost" style={{ width: '100%', justifyContent: 'center' }}>+ Add Custom Strategy</button>
              </div>
            )}

            {/* Entry Form */}
            {formStep === 'entry' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <div>
                  <label className="label">Instrument</label>
                  <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                    {INSTRUMENT_TYPES.map(t => (
                      <button key={t.value} onClick={() => set('instrument_type', t.value as any)} className={`btn btn-sm ${form.instrument_type === t.value ? 'btn-primary' : 'btn-ghost'}`}>{t.label}</button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="label">Direction</label>
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <button
                      type="button"
                      onClick={() => set('direction', 'sell')}
                      className={`btn btn-sm ${form.direction === 'sell' ? 'btn-primary' : 'btn-ghost'}`}
                      style={{ flex: 1, justifyContent: 'center' }}>
                      ↓ Sell {baseCcy}
                    </button>
                    <button
                      type="button"
                      onClick={() => set('direction', 'buy')}
                      className={`btn btn-sm ${form.direction === 'buy' ? 'btn-primary' : 'btn-ghost'}`}
                      style={{ flex: 1, justifyContent: 'center' }}>
                      ↑ Buy {baseCcy}
                    </button>
                  </div>
                  <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>
                    {form.direction === 'sell'
                      ? `You are selling ${baseCcy} and receiving ${quoteCcy}`
                      : `You are buying ${baseCcy} and paying ${quoteCcy}`}
                  </p>
                </div>

                <div>
                  <label className="label">Currency Pair</label>
                  <select className="input" value={form.currency_pair} onChange={e => set('currency_pair', e.target.value)}>
                    {CURRENCY_PAIRS.map(p => <option key={p}>{p}</option>)}
                  </select>
                </div>

                <div>
                  <label className="label">Notional Amount ({baseCcy})</label>
                  <input className="input" type="number" placeholder="e.g. 150000" value={form.notional_base || ''} onChange={e => set('notional_base', parseFloat(e.target.value) || 0)} />
                </div>

                <div>
                  <label className="label" style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span>RFQ Rate</span>
                    {quotedNotional > 0 && <span style={{ color: 'var(--teal-dark)', fontWeight: 400, fontSize: '0.75rem' }}>≈ {formatCurrency(quotedNotional, quoteCcy, true)} {quoteCcy}</span>}
                  </label>
                  <div style={{ position: 'relative' }}>
                    <input className="input" type="number" step="0.0001" placeholder="e.g. 1.3625" value={form.contracted_rate || ''} onChange={e => set('contracted_rate', parseFloat(e.target.value) || 0)} style={{ paddingRight: '2.5rem' }} />
                    <button
                      title="Fill live spot rate"
                      style={{ position: 'absolute', right: '0.5rem', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--teal)' }}
                      onClick={() => { const r = ratesMap[form.currency_pair]; if (r) set('contracted_rate', parseFloat(r.toFixed(4))) }}
                    ><RefreshCw size={13} /></button>
                  </div>
                </div>

                <div>
                  <label className="label">Your Total Fee (CAD)</label>
                  <input className="input" type="number" placeholder="e.g. 200"
                    value={fee} onChange={e => setFee(parseFloat(e.target.value) || 0)} />
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
                  <div>
                    <label className="label">Trade Date</label>
                    <input className="input" type="date" value={form.trade_date} onChange={e => set('trade_date', e.target.value)} />
                  </div>
                  <div>
                    <label className="label">Settlement Date</label>
                    <input className="input" type="date" value={form.value_date} onChange={e => set('value_date', e.target.value)} />
                  </div>
                </div>

                <div>
                  <label className="label">Counterparty Bank</label>
                  <select className="input" value={form.counterparty_bank ?? ''} onChange={e => set('counterparty_bank', e.target.value)}>
                    <option value="">Select…</option>
                    {BANKS.map(b => <option key={b}>{b}</option>)}
                  </select>
                </div>

                {formError && <div style={{ background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 'var(--r-sm)', padding: '0.625rem 0.875rem', fontSize: '0.875rem', color: 'var(--red)' }}>{formError}</div>}

                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="btn btn-ghost" onClick={() => setFormStep('select-strategy')}>← Back</button>
                  <button className="btn btn-primary" style={{ flex: 1, justifyContent: 'center' }} onClick={handleSubmit}>Review →</button>
                </div>
              </div>
            )}

            {/* Review */}
            {formStep === 'review' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.875rem' }}>
                <div style={{ background: 'var(--bg-surface)', borderRadius: 'var(--r-md)', padding: '1rem', border: '1px solid var(--border)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.625rem' }}>
                    <span style={{ color: 'var(--text-muted)', fontSize: '0.8125rem' }}>
                      {form.direction === 'sell' ? `Sell ${baseCcy}` : `Pay ${quoteCcy}`}
                    </span>
                    <span style={{ fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
                      {form.direction === 'sell'
                        ? formatCurrency(form.notional_base, baseCcy)
                        : formatCurrency(quotedNotional, quoteCcy)}
                    </span>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                    <span style={{ color: 'var(--text-muted)', fontSize: '0.8125rem' }}>
                      {form.direction === 'sell' ? `Receive ${quoteCcy}` : `Buy ${baseCcy}`}
                    </span>
                    <span style={{ fontWeight: 700, fontFamily: 'var(--font-mono)', color: 'var(--teal-dark)' }}>
                      {form.direction === 'sell'
                        ? formatCurrency(quotedNotional, quoteCcy)
                        : formatCurrency(form.notional_base, baseCcy)}
                    </span>
                  </div>
                </div>

                {[
                  { label: 'Spot Rate', value: form.contracted_rate?.toFixed(6) },
                  { label: 'All In Rate', value: ((form.contracted_rate ?? 0) - 0.05).toFixed(6) },
                  { label: 'Forward Points', value: '48.6355' },
                  { label: 'Settlement Date', value: form.value_date ? formatDate(form.value_date) : '—' },
                  { label: 'Counterparty', value: form.counterparty_bank || '—' },
                  { label: 'Total Fee', value: fee > 0 ? `CAD ${formatCurrency(fee, 'CAD')}` : '—' },
                ].map(r => (
                  <div key={r.label} style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.875rem', padding: '0.25rem 0', borderBottom: '1px solid var(--border-dim)' }}>
                    <span style={{ color: 'var(--text-muted)' }}>{r.label}</span>
                    <span style={{ fontWeight: 500, fontFamily: 'var(--font-mono)' }}>{r.value}</span>
                  </div>
                ))}

                {formError && <div style={{ background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 'var(--r-sm)', padding: '0.625rem 0.875rem', fontSize: '0.875rem', color: 'var(--red)' }}>{formError}</div>}

                <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.25rem' }}>
                  <button className="btn btn-ghost" onClick={() => setFormStep('entry')}>← Back</button>
                  <button className="btn btn-primary" style={{ flex: 1, justifyContent: 'center' }} onClick={handleSubmit} disabled={submitting}>
                    {submitting ? <span className="spinner" style={{ width: 16, height: 16 }} /> : '✓ Confirm'}
                  </button>
                </div>
              </div>
            )}

            {/* Success */}
            {formStep === 'success' && (
              <div style={{ textAlign: 'center' }}>
                <div style={{ width: 64, height: 64, borderRadius: '50%', background: '#10b981', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1rem' }}>
                  <svg width="32" height="32" viewBox="0 0 32 32" fill="none"><path d="M6 16l7 7L26 9" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></svg>
                </div>
                <h3 style={{ fontWeight: 700, fontSize: '1.125rem', marginBottom: '0.375rem' }}>Transaction Sent</h3>
                <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginBottom: '1.5rem' }}>Your hedge position has been confirmed and saved.</p>
                <div style={{ background: 'var(--bg-surface)', borderRadius: 'var(--r-md)', padding: '1rem', border: '1px solid var(--border)', marginBottom: '1.5rem', textAlign: 'left' }}>
                  {[
                    { label: 'Buy', value: `${quoteCcy} ${formatCurrency(quotedNotional, quoteCcy)}` },
                    { label: 'Sell', value: `${baseCcy} ${formatCurrency(form.notional_base, baseCcy)}` },
                    { label: 'Locked Rate', value: form.contracted_rate?.toFixed(6) },
                    { label: 'Fee', value: 'CAD $200' },
                    { label: 'Settlement Date', value: form.value_date ? formatDate(form.value_date) : '—' },
                  ].map(r => (
                    <div key={r.label} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.375rem 0', borderBottom: '1px solid var(--border-dim)', fontSize: '0.875rem' }}>
                      <span style={{ color: 'var(--text-muted)' }}>{r.label}</span>
                      <span style={{ fontWeight: 600, fontFamily: 'var(--font-mono)' }}>{r.value}</span>
                    </div>
                  ))}
                </div>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button className="btn btn-ghost" style={{ flex: 1 }} onClick={closeForm}>Done</button>
                  <a href="/trade" className="btn btn-primary" style={{ flex: 1, justifyContent: 'center', textDecoration: 'none' }}>View Trade Status</a>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
